# Generated by Django 6.0.1 on 2026-02-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
